/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author DatPC
 */
public class Form_QuanLyMay extends javax.swing.JPanel {

    /**
     * Creates new form Form_QuanLyMay
     */
    public Form_QuanLyMay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        psp8 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        psp1 = new javax.swing.JToggleButton();
        psp2 = new javax.swing.JToggleButton();
        psp3 = new javax.swing.JToggleButton();
        psp4 = new javax.swing.JToggleButton();
        psp5 = new javax.swing.JToggleButton();
        psp6 = new javax.swing.JToggleButton();
        psp7 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(73, 128, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        psp8.setBackground(new java.awt.Color(204, 204, 204));
        psp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp8MouseClicked(evt);
            }
        });
        psp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp8ActionPerformed(evt);
            }
        });
        jPanel2.add(psp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 120, 100));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 720, -1));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 720, -1));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, 450));

        psp1.setBackground(new java.awt.Color(204, 204, 204));
        psp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp1MouseClicked(evt);
            }
        });
        psp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp1ActionPerformed(evt);
            }
        });
        jPanel2.add(psp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, 100));

        psp2.setBackground(new java.awt.Color(204, 204, 204));
        psp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp2MouseClicked(evt);
            }
        });
        psp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp2ActionPerformed(evt);
            }
        });
        jPanel2.add(psp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 100));

        psp3.setBackground(new java.awt.Color(204, 204, 204));
        psp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp3MouseClicked(evt);
            }
        });
        psp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp3ActionPerformed(evt);
            }
        });
        jPanel2.add(psp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, 100));

        psp4.setBackground(new java.awt.Color(204, 204, 204));
        psp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp4MouseClicked(evt);
            }
        });
        psp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp4ActionPerformed(evt);
            }
        });
        jPanel2.add(psp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 120, 100));

        psp5.setBackground(new java.awt.Color(204, 204, 204));
        psp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp5MouseClicked(evt);
            }
        });
        psp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp5ActionPerformed(evt);
            }
        });
        jPanel2.add(psp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 120, 100));

        psp6.setBackground(new java.awt.Color(204, 204, 204));
        psp6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp6MouseClicked(evt);
            }
        });
        psp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp6ActionPerformed(evt);
            }
        });
        jPanel2.add(psp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 120, 100));

        psp7.setBackground(new java.awt.Color(204, 204, 204));
        psp7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-psp-100.png"))); // NOI18N
        psp7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psp7MouseClicked(evt);
            }
        });
        psp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psp7ActionPerformed(evt);
            }
        });
        jPanel2.add(psp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 100));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MỞ MÁY");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setFocusCycleRoot(true);
        jButton1.setRolloverEnabled(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 110, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MENU");
        jButton2.setBorderPainted(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 110, 40));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("TÍNH BILL");
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(true);
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 120, 40));

        jPanel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("SỐ MÁY HOẠT ĐỘNG");
        jPanel7.add(jLabel1);

        jTextField1.setText("0");
        jTextField1.setEnabled(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField1);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PSP4_4");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PSP5_4");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PSP4_2");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PSP4_3");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PSP4_1");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PSP5_1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PSP5_2");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PSP5_3");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void psp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp8ActionPerformed

    private void psp8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp8MouseClicked
        // TODO add your handling code here:
        if(!psp8.isSelected())
            psp8.setIcon(new ImageIcon("src/Icon/psp_on.png"));
        else{
            psp8.setIcon(new ImageIcon("src/Icon/icons8-psp-100.png"));
        }
    }//GEN-LAST:event_psp8MouseClicked

    private void psp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp1MouseClicked

    private void psp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp1ActionPerformed

    private void psp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp2MouseClicked

    private void psp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp2ActionPerformed

    private void psp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp3MouseClicked

    private void psp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp3ActionPerformed

    private void psp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp4MouseClicked

    private void psp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp4ActionPerformed

    private void psp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp5MouseClicked

    private void psp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp5ActionPerformed

    private void psp6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp6MouseClicked

    private void psp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp6ActionPerformed

    private void psp7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psp7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_psp7MouseClicked

    private void psp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psp7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton psp1;
    private javax.swing.JToggleButton psp2;
    private javax.swing.JToggleButton psp3;
    private javax.swing.JToggleButton psp4;
    private javax.swing.JToggleButton psp5;
    private javax.swing.JToggleButton psp6;
    private javax.swing.JToggleButton psp7;
    private javax.swing.JToggleButton psp8;
    // End of variables declaration//GEN-END:variables
}
